version: '3.8'
name: mobina
services:
  web:
    build: .
    ports:
      - "5000"
    deploy:
      replicas: 4
    depends_on:
      - mysql

  mysql: 
    container_name: sqlserver
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Pass"
      MYSQL_USER: mobina
      MYSQL_PASSWORD: Pass2
    volumes:
      - ./initialdb:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql

  nginx: 
    container_name: nginx
    image: nginx
    ports:
      - 8888:80
    depends_on:
      - mysql
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf