name: mobina
services:
  web:
    build: .
    ports:
      - "5000"
    deploy:
      replicas: 4
    depends_on:
      - mysql-master
 
  mysql-master:
    image: 'bitnami/mysql:latest'
    container_name: mysql-master
    ports:
      - '3306'
    volumes:
      - ./data:/bitnami/mysql/data
      - ./initialdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=mobina
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=mobina
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=my_database

  mysql-slave:
    image: 'bitnami/mysql:latest'
    container_name: mysql-slave
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=mobina
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=pass
    
  nginx: 
    container_name: nginx
    image: nginx
    ports:
      - 8888:80
    depends_on:
      - mysql-master
      - web
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf