apiVersion: v1
kind: ConfigMap
metadata:
  name: dbcreate
data:
  createdb.sql: |
    CREATE DATABASE loginapp;
    USE loginapp; 
    CREATE TABLE accounts (
      id INT PRIMARY KEY AUTO_INCREMENT,
      username VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL
    );